version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: ${DOCKER_MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  app:
    image: node:latest
    environment:
      DEPLOY: DOCKER
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm run start && npm run migrate && npm run seed"
    links: 
      - db
    env_file: .env
volumes:
  db-data: